import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,NavLink,Route,Routes}from'react-router-dom';
import{WagmiProvider,createConfig,http,useAccount,useChainId,useConnect,useDisconnect,useSwitchChain}from'wagmi';
import{injected}from'wagmi/connectors';
import{QueryClient,QueryClientProvider}from'@tanstack/react-query';
import'./styles.css';

const arc={id:5042002,name:'Arc Testnet',nativeCurrency:{name:'USDC',symbol:'USDC',decimals:18},rpcUrls:{default:{http:['https://rpc.testnet.arc.network']},public:{http:['https://rpc.testnet.arc.network']}},blockExplorers:{default:{name:'ArcScan',url:'https://testnet.arcscan.app'}},testnet:true};
const config=createConfig({chains:[arc],connectors:[injected()],transports:{[arc.id]:http()}});const queryClient=new QueryClient();
const network={chain:arc,label:'ARC',money:'USDC',gas:'USDC',settlement:'SUB-SECOND',accent:'STABLECOIN-NATIVE'};
const coins=[['PEPE.exe','PEPX','$0.004218','+18.4'],['GIGA BRAIN','GBRN','$0.08801','+9.7'],['RUG PROOF','RUGP','$0.00091','-4.2'],['404 DOG','DOG4','$0.02024','+6.9']];
const nfts=[['NO SIGNAL #033','120 USDC'],['BASED SPECIMEN #19','80 USDC'],['TERMINAL FROG #808','210 USDC']];
function Mascot({small=false}){return <img className={'mascot pixel-mark '+(small?'small':'')} src="/memeverse/memeverse-mark.png" alt="MemeVerse pixel-grid mark"/>}
function Marquee(){return <div className="marquee"><div>{[...coins,...coins].map((c,i)=><span key={i}>{c[1]} <b>{c[2]}</b> <em className={c[3][0]=='-'?'down':'up'}>{c[3]}%</em></span>)}</div></div>}
function Wallet(){const{address,isConnected}=useAccount();const{connect,isPending}=useConnect();const{disconnect}=useDisconnect();return isConnected?<button className="wallet" onClick={()=>disconnect()}><i/>LIVE {address.slice(0,6)}…{address.slice(-4)}</button>:<button className="wallet" onClick={()=>connect({connector:injected()})}>{isPending?'REQUESTING…':'CONNECT WALLET'}</button>}
function NetworkStatus(){const chainId=useChainId();const{switchChain}=useSwitchChain();const onArc=chainId===arc.id;return <div className="network-switch" aria-label="Arc Network status"><button className={onArc?'active':''} onClick={()=>switchChain?.({chainId:arc.id})}><i/>BUILT ON ARC{onArc&&<sup>ON</sup>}</button></div>}
function Shell(){return <><Marquee/><div className="network-bar"><span>INFRASTRUCTURE</span><NetworkStatus/><span>{network.accent} // GAS: {network.gas}</span></div><header><NavLink className="brand" to="/"><img className="brand-lockup" src="/memeverse/memeverse-lockup.png" alt="MemeVerse"/></NavLink><nav>{[['01','LAUNCH','/launch'],['02','TRADE','/trade'],['03','NFT','/nft'],['04','VAULT','/vault'],['05','AGENT','/agent']].map(x=><NavLink key={x[1]} to={x[2]}><sup>{x[0]}</sup>{x[1]}</NavLink>)}</nav><Wallet/></header><main><Routes><Route path="/" element={<Home/>}/><Route path="/launch" element={<Launch/>}/><Route path="/trade" element={<Trade/>}/><Route path="/nft" element={<NFT/>}/><Route path="/vault" element={<Vault/>}/><Route path="/agent" element={<Agent/>}/></Routes></main><footer><span>MEMEVERSE © 2026</span><span>{network.chain.name.toUpperCase()} // CHAIN {network.chain.id}</span><span>BUILT ON ARC // USDC SETTLEMENT</span></footer></>}
function Stat({n,l}){return <div><strong>{n}</strong><small>{l}</small></div>}
function Home(){return <><section className="hero"><div><div className="eyebrow">{network.chain.name.toUpperCase()} / CHAIN {network.chain.id}</div><h1>MEMES ARE<br/><mark>FINANCIAL</mark><br/>PRIMITIVES.</h1><p>Launch and trade culture with USDC as the money, gas and settlement layer. Autonomous agents settle creator jobs without human intervention.</p><NavLink className="btn primary" to="/launch">DEPLOY ON {network.label} →</NavLink></div><aside><Mascot/><p>SETTLEMENT_LAYER: {network.label}<br/>STATUS: <b className="acid">LIVE</b></p></aside></section><section className="stats"><Stat n="$4.8M USDC" l="24H VOLUME"/><Stat n="12,904" l="DEGENS ONLINE"/><Stat n="420" l="COINS LAUNCHED"/><Stat n={network.settlement} l="AVG. FINALITY"/></section><section className="split"><div><Title n="05" t="TRENDING COINS"/><div className="coin-table">{coins.map((c,i)=><div className="coin-row" key={c[0]}><span className="rank">0{i+1}</span><span><b>{c[0]}</b><small>${c[1]}</small></span><strong>{c[2]}</strong><em className={c[3][0]=='-'?'down':'up'}>{c[3][0]=='-'?'▼':'▲'} {c[3]}%</em><button>TRADE</button></div>)}</div></div><div><Title n="06" t="LATEST DROPS"/>{nfts.slice(0,2).map((x,i)=><NFTCard key={x[0]} n={x[0]} p={x[1]} i={i}/>)}</div></section></>}
function Title({n,t}){return <div className="title"><span>{n}</span><h2>{t}</h2><i/></div>}
function Launch(){const[name,setName]=useState('');const[symbol,setSymbol]=useState('');const[supply,setSupply]=useState('1000000000');const[done,setDone]=useState(false);return <section className="page"><Title n="01" t="LAUNCH A MEME"/><div className="form-grid"><form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>MEME NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. UNEMPLOYED CAT" required/></label><label>TICKER<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="UCAT" maxLength="6" required/></label><label>TOTAL SUPPLY<input value={supply} onChange={e=>setSupply(e.target.value)} type="number"/></label><label>LORE / DESCRIPTION<textarea placeholder="Why does this deserve liquidity?"/></label><div className="receive"><span>YOU RECEIVE</span><b>{Number(supply||0).toLocaleString()} ${symbol||'TOKEN'}</b></div><button className="btn primary full">DEPLOY ON {network.label} →</button>{done&&<div className="receipt">TX ACCEPTED // <a href={network.chain.blockExplorers.default.url} target="_blank" rel="noreferrer">0x8f31…a04c ↗</a></div>}</form><aside className="spec"><span>DEPLOYMENT SPEC</span><dl><dt>CURVE</dt><dd>LINEAR</dd><dt>CREATOR FEE</dt><dd>1.00%</dd><dt>NETWORK</dt><dd>{network.chain.name}</dd><dt>SETTLEMENT</dt><dd>USDC</dd><dt>EST. GAS</dt><dd>0.0012 USDC</dd></dl><Mascot/></aside></div></section>}
function Chart(){return <svg className="chart" viewBox="0 0 800 360" preserveAspectRatio="none"><g className="grid">{[60,120,180,240,300].map(y=><line key={y} x1="0" y1={y} x2="800" y2={y}/>)}</g><polyline points="0,290 70,278 130,240 190,260 250,192 310,210 370,130 430,151 490,100 550,120 610,63 670,91 735,41 800,54"/></svg>}
function Trade(){const[side,setSide]=useState('BUY');const[amount,setAmount]=useState('25');return <section className="page"><Title n="02" t="TRADE / PEPX"/><div className="trade-grid"><div className="chartbox"><div className="quote"><span>PEPE.exe / USD</span><b>$0.004218</b><em className="up">▲ 18.4%</em></div><Chart/><div className="axis">00:00　04:00　08:00　12:00　16:00　20:00　NOW</div></div><div className="order"><div className="tabs"><button className={side==='BUY'?'active':''} onClick={()=>setSide('BUY')}>BUY</button><button className={side==='SELL'?'sell':''} onClick={()=>setSide('SELL')}>SELL</button></div><label>YOU PAY<input value={amount} onChange={e=>setAmount(e.target.value)}/><small>{network.money}</small></label><div className="receive"><span>YOU RECEIVE</span><b>{(Number(amount||0)*237).toFixed(0)} PEPX</b></div><dl><dt>CURVE PROGRESS</dt><dd>68.4%</dd><dt>PRICE IMPACT</dt><dd>0.82%</dd><dt>MIN. RECEIVED</dt><dd>58,716 PEPX</dd></dl><button className="btn primary full">{side} PEPX →</button></div></div></section>}
function NFTCard({n,p,i}){return <article className="nft-card"><div className={'art art'+i}><Mascot/></div><div><small>MEMEVERSE ARCHIVE</small><h3>{n}</h3><b>{p}</b><button>MINT</button></div></article>}
function NFT(){const[modal,setModal]=useState(false);return <section className="page"><Title n="03" t="NFT ARCHIVE"/><div className="nft-grid">{[...nfts,['LIQUIDITY GOBLIN #2','160 USDC'],['EXIT SIGNAL #69','110 USDC'],['DEGEN RELIC #404','320 USDC']].map((x,i)=><div key={x[0]} onClick={()=>setModal(true)}><NFTCard n={x[0]} p={x[1]} i={i%3}/></div>)}</div>{modal&&<div className="modal" onClick={()=>setModal(false)}><div onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(false)}>×</button><Title n="LIST" t="SET ASK PRICE"/><label>PRICE<input placeholder="0.00"/><small>USDC</small></label><button className="btn primary full">LIST FOR SALE →</button></div></div>}</section>}
function Vault(){const[tab,setTab]=useState('TOKENS');return <section className="page"><Title n="04" t="MY ASSETS"/><div className="big-tabs"><button className={tab==='TOKENS'?'active':''} onClick={()=>setTab('TOKENS')}>TOKENS / 03</button><button className={tab==='NFTS'?'active':''} onClick={()=>setTab('NFTS')}>NFTS / 02</button></div>{tab==='TOKENS'?<div className="assets">{coins.slice(0,3).map((c,i)=><div key={c[0]}><b>{c[0]} <small>${c[1]}</small></b><strong>{[238400,91420,404808][i].toLocaleString()}</strong><span>{c[2]}</span><button>TRADE ↗</button></div>)}</div>:<div className="nft-grid">{nfts.slice(0,2).map((x,i)=><NFTCard key={x[0]} n={x[0]} p={x[1]} i={i}/>)}</div>}<div className="empty"><Mascot small/><span>ACTIVE LISTINGS: 0<br/>NOTHING ESCAPING THE VAULT.</span></div></section>}
function Agent(){const[ran,setRan]=useState(false);return <section className="page agent-page"><Title n="05" t="AUTONOMOUS SETTLEMENT"/><p className="lede">An onchain curator agent scores meme traction, allocates a capped treasury, and settles creator jobs in {network.money} under explicit risk rules.</p><div className="agent-grid"><div className="agent-rules"><span>DECISION POLICY / V1.0</span><label>MAX SPEND / RUN<input defaultValue="25.00"/><small>{network.money}</small></label><label>MIN. VIRALITY SCORE<input defaultValue="78"/><small>/100</small></label><label>CREATOR SETTLEMENT<input defaultValue="60"/><small>%</small></label><dl><dt>SIGNAL</dt><dd>VOLUME + HOLDERS</dd><dt>RISK LIMIT</dt><dd>2.5% TREASURY</dd><dt>EXECUTION</dt><dd>NON-CUSTODIAL</dd><dt>NETWORK</dt><dd>{network.chain.name}</dd></dl><button className="btn primary full" onClick={()=>setRan(true)}>RUN AGENT SIMULATION →</button></div><div className="agent-log"><span>EXECUTION TRACE</span>{[['01','INGEST SIGNAL','PEPX / SCORE 84'],['02','CHECK POLICY','PASS / CAP OK'],['03','ALLOCATE','25.00 USDC'],['04','SETTLE CREATOR','15.00 USDC'],['05','RETAIN TREASURY','10.00 USDC']].map(x=><div className={ran?'done':''} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><strong>{ran?x[2]:'PENDING'}</strong></div>)}<div className="agent-status">{ran?'POLICY EXECUTED // READY FOR ONCHAIN SIGNATURE':'AWAITING SIGNAL // SIMULATION MODE'}</div></div></div><div className="stack-strip"><span>BUILT ON ARC</span><span>USDC GAS</span><span>CIRCLE APP KITS</span><span>AGENT WALLET</span><span>CONDITIONAL SETTLEMENT</span></div></section>}
createRoot(document.getElementById('root')).render(<React.StrictMode><WagmiProvider config={config}><QueryClientProvider client={queryClient}><BrowserRouter><Shell/></BrowserRouter></QueryClientProvider></WagmiProvider></React.StrictMode>);
